services:
  - type: web
    name: llama-importaciones
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://llamaimportaciones.onrender.com/api
