services:
  - type: web
    name: llama-importaciones
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: /api
      - key: VITE_GOOGLE_CLIENT_ID
        value: 354015976108-epog0rvn626k5qfrbi88m6pa3ietv43n.apps.googleusercontent.com
